config/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('skinset/', include('skinset.urls')),
    path('admin/', admin.site.urls),
]

config/skinset/urls.py
from django.urls import path

from . import views

app_name = 'skinset'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/<kind>/<int:identifier>', views.list, name='list'),
    path('crop/<int:identifier>', views.crop_image, name='crop_image'),
    path('by-image/<path:image_path>', views.by_image, name='by_image'),
    path('img/<path:path>', views.image, name='img'),
]

config/skinset/models.py
from django.db import models


class ImageCategory(models.Model):
    category = models.CharField(max_length=128)

    def __str__(self):
        return self.category


class SkinCategory(models.Model):
    category = models.CharField(max_length=128)

    def __str__(self):
        return self.category


class Skin(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey('SkinCategory', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CropImage(models.Model):
    name = models.CharField(max_length=128)
    imgrect = models.CharField(max_length=64)
    file = models.CharField(max_length=256)
    source_path = models.CharField(max_length=256)
    image_category = models.ForeignKey('ImageCategory', on_delete=models.CASCADE, null=True)
    skin = models.ForeignKey('Skin', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

config/skinset/views.py
from PIL import Image
from django.shortcuts import HttpResponse
from django.shortcuts import render

from .models import ImageCategory, Skin, CropImage


def index(request):
    """
    indexのHttpResponseを返す.
    :param request: HttpRequest.
    :return: indexのHttpResponse.
    """
    image_categories = ImageCategory.objects.order_by('category')
    skins = Skin.objects.order_by('category')
    skin_files = CropImage.objects.filter(skin__isnull=False) \
        .values('file').order_by('file').distinct()

    context = {
        'image_categories': image_categories,
        'skins': skins,
        'skin_files': skin_files
    }
    return render(request, 'skinset/index.html', context)


def list(request, kind, identifier):
    """
    各一覧画面のHttpResponseを返す.
    :param request: HttpRequest.
    :param kind: 表示するデータ種別. 'image', 'skin'のいずれか.
    :param identifier: typeが'image'の場合はImageCategoryのID、'skin'の場合はSkinのID.
    :return: 一覧画面のHttpResponse.
    """
    context = {}

    if kind == 'image':
        context = {
            'image_list': CropImage.objects.filter(image_category=identifier).order_by('name'),
            'category_name': ImageCategory.objects.get(id=identifier).category
        }
    elif kind == 'skin':
        context = {
            'image_list': CropImage.objects.filter(skin=identifier).order_by('name'),
            'category_name': Skin.objects.get(id=identifier).name
        }
    else:
        pass

    return render(request, 'skinset/list.html', context)


def by_image(request, image_path):
    """
    指定した画像ファイルを参照しているSkinの一覧を表示するViewを返す.
    :param request: HttpRequest.
    :param image_path: 画像ファイルのパス.
    :return: Skin一覧を表示するView.
    """
    context = {
        'path': image_path,
        'crop_image_list': CropImage.objects.filter(file=image_path).filter(skin__isnull=False).order_by('skin')
    }

    return render(request, 'skinset/by-image.html', context)

def image(request, path):
    """
    指定したパスに格納されているファイルを画像として扱い、画像をHttpResponseとして返す.
    :param request: HttpRequest.
    :param path: ファイルパス. ui.ipfからの相対パスとして指定する.
    :return: 画像のHttpResponse.
    """
    im = Image.open('./static/skinset/ui.ipf/' + path)
    res = HttpResponse(content_type='image/png')
    im.save(res, 'PNG')
    return res


def crop_image(request, identifier):
    """
    指定したCropImageのIDに対応する画像をHttpResponseとして返す.
    :param request: HttpRequest.
    :param identifier: CropImageのID.
    :return: トリミング済み画像のHttpResponse.
    """
    record = CropImage.objects.filter(id=identifier)[0]

    l, t, w, h = [int(s) for s in record.imgrect.split()]
    im = Image.open('./static/skinset/ui.ipf/' + record.file)
    im = im.crop((l, t, (l + w), (t + h)))
    response = HttpResponse(content_type='image/png')
    im.save(response, 'PNG')

    return response

config/skinset/templates/skinset/by-image.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ path }}</h1>

<h2>Full image</h2>
{% url 'skinset:img' path as the_url %}
<a href="{{ the_url }}"><img src="{{ the_url }}" alt="{{ path }}" width="50%"/></a>

<h2>Referenced</h2>
<ul>
    {% regroup crop_image_list by category.category as skins_by_category %}
    {% for category, skins in skins_by_category %}
    <li>Category: {{ category }}</li>
    <ul>
        {% regroup skins by skin.name as skins_by_name %}
        {% for name, skins in skins_by_name %}
        <li>Name: {{ name }}</li>
        <ul>
            {% for crop_image in skins %}
            {% url 'skinset:crop_image' crop_image.id as the_url %}
            <li>
                {{ crop_image.name }}<br>
                <a href="{{ the_url }}"><img src="{{ the_url }}" alt="{{ path }}"/></a>
            </li>
            {% endfor %}
        </ul>
        {% endfor %}
    </ul>
    {% empty %}
    <li>empty</li>
    {% endfor %}
</ul>

config/skinset/templates/skinset/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>ToS Data Viewer</h1>

<h2>Images</h2>
<ul>
    {% for category in image_categories %}
    {% url 'skinset:list' 'image' category.id as the_url %}
    <li><a href="{{ the_url }}">{{ category.category }}</a></li>
    {% empty %}
    <li>empty</li>
    {% endfor %}
</ul>

<h2>Skins</h2>
<ul>
    {% regroup skins by category.category as skins_by_category %}
    {% for category, skins in skins_by_category %}
    <li>{{ category }}</li>
    <ul>
        {% for skin in skins %}
        {% url 'skinset:list' 'skin' skin.id as the_url %}
        <li><a href="{{ the_url }}">{{ skin.name }}</a></li>
        {% endfor %}
    </ul>
    {% empty %}
    <li>empty</li>
    {% endfor %}
</ul>

<h2>Skins (group by file)</h2>
<ul>
    {% for skin in skin_files %}
    {% url 'skinset:by_image' skin.file as the_url %}
    <li><a href="{{ the_url }}">{{ skin.file }}</a></li>
    {% empty %}
    <li>empty</li>
    {% endfor %}
</ul>

config/skinset/templates/skinset/list.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ category_name }}</h1>
<ul>
{% for image in image_list %}
    {% url 'skinset:crop_image' image.id as the_url %}
    <li>{{ image.name }}<br><a href="{{ the_url }}"><img src="{{ the_url }}" alt="{{ image.file }}"/></a></li>
{% empty %}
    <li>No images are available.</li>
{% endfor %}
</ul>